@extends('layouts.app')

@section('content')
<main class="management-page">
    <div class="management-header"><div><span class="management-kicker">Consulta de registro</span><h1>{{ $trainingCenter->name }}</h1><p>Detalle del centro de formación y sus relaciones actuales.</p></div><a href="{{ route('trainingCenter.index') }}" class="management-secondary-action">Volver a centros</a></div>
    <section class="detail-card">
        <div class="detail-card-heading"><div class="detail-record-icon">{{ strtoupper(substr($trainingCenter->name, 0, 1)) }}</div><div><span class="detail-label">Centro registrado</span><h2>{{ $trainingCenter->name }}</h2><p class="detail-description">{{ $trainingCenter->location }}</p></div></div>
        <div class="detail-stats"><div class="detail-stat"><span>Identificador</span><strong>#{{ str_pad($trainingCenter->id, 3, '0', STR_PAD_LEFT) }}</strong></div><div class="detail-stat"><span>Cursos asociados</span><strong>{{ $trainingCenter->course->count() }}</strong></div><div class="detail-stat"><span>Instructores asociados</span><strong>{{ $trainingCenter->teacher->count() }}</strong></div><div class="detail-stat"><span>Ubicación</span><strong>{{ $trainingCenter->location }}</strong></div></div>
        <div class="related-details"><section class="related-section"><div class="related-heading"><div><span class="detail-label">Oferta académica</span><h3>Cursos asociados</h3></div><span class="related-count">{{ $trainingCenter->course->count() }}</span></div>@forelse($trainingCenter->course as $course)<div class="related-item"><span class="related-icon">C</span><div><strong>Curso {{ $course->course_number }}</strong><span>{{ $course->day ? \Carbon\Carbon::parse($course->day)->format('d/m/Y') : 'Sin fecha registrada' }}</span></div></div>@empty<p class="related-empty">No hay cursos asociados.</p>@endforelse</section><section class="related-section"><div class="related-heading"><div><span class="detail-label">Equipo humano</span><h3>Instructores asociados</h3></div><span class="related-count">{{ $trainingCenter->teacher->count() }}</span></div>@forelse($trainingCenter->teacher as $teacher)<div class="related-item"><span class="related-icon related-icon-orange">I</span><div><strong>{{ $teacher->name }}</strong><span>{{ $teacher->email }}</span></div></div>@empty<p class="related-empty">No hay instructores asociados.</p>@endforelse</section></div>
        <div class="detail-actions"><a href="{{ route('trainingCenter.edit', $trainingCenter) }}" class="management-primary-action">Editar centro</a><form action="{{ route('trainingCenter.destroy', $trainingCenter) }}" method="POST">@csrf @method('DELETE')<button type="submit" class="table-action table-action-delete" onclick="return confirm('¿Deseas eliminar este centro?')">Eliminar centro</button></form></div>
    </section>
</main>
@endsection
